name: HLSpresso CI/CD

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2

      - name: Run golangci-lint
        run: $(go env GOPATH)/bin/golangci-lint run ./...

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Get dependencies
        run: go mod download

      - name: Run Tests
        run: go test -v ./pkg/...

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: go build -v -o HLSpresso cmd/transcoder/main.go

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: HLSpresso-linux-amd64
          path: HLSpresso

  release:
    name: Build Release Binaries
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Get dependencies
        run: go mod download

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -v -o build/HLSpresso-linux-amd64 cmd/transcoder/main.go

      - name: Build for macOS (Intel)
        run: GOOS=darwin GOARCH=amd64 go build -v -o build/HLSpresso-darwin-amd64 cmd/transcoder/main.go

      - name: Build for macOS (M1/M2)
        run: GOOS=darwin GOARCH=arm64 go build -v -o build/HLSpresso-darwin-arm64 cmd/transcoder/main.go

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -v -o build/HLSpresso-windows-amd64.exe cmd/transcoder/main.go

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/HLSpresso-linux-amd64
            build/HLSpresso-darwin-amd64
            build/HLSpresso-darwin-arm64
            build/HLSpresso-windows-amd64.exe
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 